/** Tarefa 6 — curadoria pedagógica do Domínio 1 (Agentic Architecture &
 * Orchestration) das 60 questões de `exame-avancado/dominio-1_gabarito.md`.
 *
 * Cada entrada preenche o que `exame-avancado/` não traz: parágrafo de
 * abertura (resumo), os 5 campos do bloco de Metadados, `topicos` e
 * `arquetipos` por alternativa errada (id canônico de
 * `src/domain/arquetipos.ts`, nunca a alternativa correta). Consumido por
 * `scripts/aplicar-curadoria.mts`, que injeta isto no gabarito já convertido
 * pela Tarefa 5 (`content/exame-avancado/dominio-1/dominio-1_gabarito.md`).
 */
import type { Curadoria } from "../tipoCuradoria";

const D1: Curadoria[] = [
  { n: 1, correta: "D", resumo: "O sinal confiável para decidir se o loop deve continuar é o `stop_reason` da API, não a presença de texto na resposta: enquanto for `tool_use` existe uma chamada pendente para executar; `end_turn` sinaliza conclusão.", bloom: "Analisar", dificuldade: "Médio", cenario: "S1 — Customer Support Resolution Agent", principio: "`stop_reason` como sinal determinístico de parada do loop (nunca presença de texto)", topicos: ["Loop Agêntico"], arquetipos: { A: "over-engineering", B: "probabilistico-vs-garantia", C: "camada-alvo-errado" } },
  { n: 2, correta: "D", resumo: "Subtarefas independentes que não dependem umas das outras devem sair como múltiplas chamadas de ferramenta no mesmo turno do assistente, executadas em paralelo, cortando o número de idas e voltas com a API.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S3 — Multi-Agent Research System", principio: "tool calls independentes saem em paralelo no mesmo turno, não serializadas", topicos: ["Loop Agêntico"], arquetipos: { A: "camada-alvo-errado", C: "camada-alvo-errado" } },
  { n: 3, correta: "D", resumo: "Subagentes não herdam automaticamente o contexto do coordenador nem memória entre invocações: o que \"foi discutido\" na conversa principal não existe para o subagente a menos que seja passado explicitamente no prompt de spawn.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "subagente não herda contexto do pai — só o que é passado explicitamente no spawn", topicos: ["Spawn de Subagentes"], arquetipos: { A: "feature-inexistente-verossimil", B: "camada-alvo-errado", C: "montante-jusante" } },
  { n: 4, correta: "B", resumo: "Um gate estrutural (hook `PreToolUse`) bloqueia a chamada antes que ela aconteça — é mecanismo, não pedido. Um booleano de auto-relato ou instrução de prompt continua sendo o modelo se autoavaliando, o que não é garantia.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "hook `PreToolUse` como gate estrutural — garantia, não instrução", topicos: ["Enforcement de Workflow", "Hooks"], arquetipos: { A: "sinal-nao-confiavel", C: "sinal-nao-confiavel", D: "probabilistico-vs-garantia" } },
  { n: 5, correta: "A", resumo: "Retomar um processo longo depois de uma falha exige estado durável, gravado fora da conversa, por etapa concluída — na retomada, o sistema pula direto o que já tem saída registrada em vez de refazer o trabalho.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "estado durável por etapa (fora da conversa) permite retomar sem repetir trabalho", topicos: ["Resume e Fork de Sessão"], arquetipos: { B: "camada-alvo-errado", C: "sinal-nao-confiavel", D: "camada-alvo-errado" } },
  { n: 6, correta: "D", resumo: "Decomposição estreita (\"narrow decomposition\") é o coordenador delegar só o que ele pensou em perguntar; como cada subagente só vê seu próprio contexto isolado, nenhum deles consegue sinalizar de volta um tema importante que ficou de fora do escopo.", bloom: "Analisar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "decomposição estreita esconde lacunas porque nenhum subagente vê o quadro completo para sinalizar o que falta", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "montante-jusante", B: "camada-alvo-errado", C: "camada-alvo-errado" } },
  { n: 7, correta: "B", resumo: "Um prompt procedural (uma sequência fixa de passos) quebra assim que a entrada real diverge do caminho previsto. Definir o objetivo e o critério de qualidade, em vez da sequência exata, deixa o agente decidir o caminho e redelegar quando um passo falha.", bloom: "Avaliar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "prompt goal-oriented (objetivo + critério) é mais robusto que prompt procedural (sequência fixa de passos)", topicos: ["Enforcement de Workflow"], arquetipos: { A: "camada-alvo-errado", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 8, correta: "C", resumo: "`allowedTools`/`disallowedTools` são aplicados na plataforma: se a ferramenta de edição não está no conjunto permitido do subagente, ele estruturalmente não tem como editar, independente do que o prompt ou o modelo digam.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "`allowedTools`/`disallowedTools` são enforcement de plataforma, não sugestão de prompt", topicos: ["Spawn de Subagentes", "Tool Choice"], arquetipos: { A: "camada-alvo-errado", B: "camada-alvo-errado", D: "probabilistico-vs-garantia" } },
  { n: 9, correta: "B", resumo: "Retomar uma sessão restaura a conversa registrada, não o estado atual do mundo: o modelo não sabe quanto tempo passou nem o que mudou enquanto a sessão estava parada. Por isso a retomada precisa combinar um resumo estruturado com releitura dirigida do que pode ter mudado.", bloom: "Analisar", dificuldade: "Difícil", cenario: "S4 — Developer Productivity", principio: "retomar sessão restaura a conversa, não o mundo — o modelo desconhece mudanças ocorridas enquanto estava pausado", topicos: ["Resume e Fork de Sessão"], arquetipos: { A: "montante-jusante", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 10, correta: "A", resumo: "Decomposição adaptativa dinâmica se aplica quando um achado intermediário muda o que precisa ser investigado a seguir — o caso canônico é investigação de incidente, em que a causa raiz só aparece depois de olhar os primeiros sinais.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "decomposição dinâmica: um achado intermediário redefine o próximo passo da investigação", topicos: ["Decomposição de Tarefas"], arquetipos: { B: "camada-alvo-errado", C: "camada-alvo-errado", D: "enumerar-vs-generalizar" } },
  { n: 11, correta: "B", resumo: "Dar o mesmo briefing a vários agentes de pesquisa produz respostas sobrepostas e desperdiça tokens; a correção é particionar o escopo para que cada agente cubra uma fatia distinta e sem sobreposição.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S3 — Multi-Agent Research System", principio: "particionar o escopo entre agentes de pesquisa evita sobreposição e desperdício de tokens", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "camada-alvo-errado", C: "extremo-vs-meio", D: "montante-jusante" } },
  { n: 12, correta: "B", resumo: "Uma instrução vaga como \"seja minucioso\" não é um critério verificável; uma função forçante como `evaluate_coverage`, que exige um score e uma lista de lacunas em saída estruturada antes de o loop continuar, é o que de fato detecta cobertura incompleta.", bloom: "Analisar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "função forçante com saída estruturada (score + lista de lacunas) detecta cobertura incompleta; instrução vaga não", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "probabilistico-vs-garantia", C: "camada-alvo-errado", D: "sinal-nao-confiavel" } },
  { n: 13, correta: "B", resumo: "Fork de sessão parte de um estado comum e cria ramos independentes, cada um com seu próprio histórico e identificador, isolados entre si e retomáveis — diferente de `/clear` (apaga tudo) ou de continuar sequencialmente no mesmo histórico (contamina).", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "fork de sessão cria ramos independentes e isolados a partir de um estado comum", topicos: ["Resume e Fork de Sessão"], arquetipos: { A: "camada-alvo-errado", C: "montante-jusante", D: "sinal-nao-confiavel" } },
  { n: 14, correta: "D", resumo: "Sem a ferramenta de invocação de agente (Agent/Task) disponível no conjunto do coordenador, não existe mecanismo de spawn — declarar os subagentes e instruir o coordenador a delegar não cria, por si só, o canal técnico para chamá-los.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "invocar um subagente exige a ferramenta de spawn disponível — definir o agente não basta", topicos: ["Spawn de Subagentes"], arquetipos: { A: "feature-inexistente-verossimil", B: "camada-alvo-errado", C: "camada-alvo-errado" } },
  { n: 15, correta: "D", resumo: "Numa arquitetura hub-and-spoke, o coordenador é o único ponto de passagem: toda mensagem de entrada, de saída e toda falha passam por ele, o que o torna o único lugar onde é possível inspecionar e controlar o fluxo inteiro.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "coordenador como ponto único de passagem (choke point) viabiliza observabilidade e controle", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "camada-alvo-errado", B: "extremo-vs-meio", C: "camada-alvo-errado" } },
  { n: 16, correta: "D", resumo: "Um teto de iterações é uma rede de segurança contra loops travados, mas não é lógica de controle — o critério de parada correto continua sendo o `stop_reason`; os dois mecanismos são complementares, não substitutos um do outro.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "cap de iterações é salvaguarda; `stop_reason` é o controle real de parada — os dois juntos, não um no lugar do outro", topicos: ["Loop Agêntico"], arquetipos: { B: "sinal-nao-confiavel", C: "extremo-vs-meio" } },
  { n: 17, correta: "D", resumo: "Escopo grande, risco alto e exigência de aprovação humana antes de qualquer modificação é exatamente o caso de uso do Plan Mode: o agente analisa e propõe, mas não modifica arquivos nem executa comandos até ser aprovado.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "Plan Mode: análise sem modificação, aprovação humana obrigatória antes de qualquer mudança", topicos: ["Plan Mode"], arquetipos: { A: "probabilistico-vs-garantia", B: "montante-jusante", C: "extremo-vs-meio" } },
  { n: 18, correta: "B", resumo: "Um protocolo de handoff é um pacote estruturado que o agente monta antes de escalar para um humano — contexto, ações já tentadas, o bloqueio e a decisão necessária — para que quem recebe não precise vasculhar o histórico inteiro da conversa.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S1 — Customer Support Resolution Agent", principio: "handoff estruturado (contexto + ações tentadas + bloqueio + decisão) evita reconstrução manual do caso pelo humano", topicos: ["Enforcement de Workflow"], arquetipos: { A: "montante-jusante", C: "vazio-ausente", D: "camada-alvo-errado" } },
  { n: 19, correta: "A", resumo: "Diante da falha de um subagente, o padrão recomendado é tentar de novo localmente, depois um fallback, e só escalar para um humano quando as tentativas se esgotarem — nunca propagar tudo indiscriminadamente nem mascarar a falha como se fosse sucesso.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "retry local → fallback → escalonamento só quando as tentativas se esgotam", topicos: ["Propagação de Erros"], arquetipos: { B: "vazio-ausente", C: "over-engineering", D: "vazio-ausente" } },
  { n: 20, correta: "C", resumo: "Encadeamento de prompts (prompt chaining) serve quando a forma do trabalho é fixa independente do conteúdo — ETL, transformação de documento — que é exatamente o caso de um pipeline de processamento em etapas fixas e sequenciais.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S6 — Structured Data Extraction", principio: "prompt chaining é adequado quando a forma do trabalho é fixa, independente do conteúdo processado", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "over-engineering", B: "over-engineering", D: "camada-alvo-errado" } },
  { n: 21, correta: "B", resumo: "Seleção dinâmica de orquestração é o coordenador escolher, em tempo de execução, a forma da orquestração — agente único para tarefa simples, sequencial para multi-etapa dependente, paralelo para subtarefas independentes.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "o coordenador escolhe a forma da orquestração (único/sequencial/paralelo) dinamicamente, não fixa de antemão", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "camada-alvo-errado", C: "camada-alvo-errado", D: "vazio-ausente" } },
  { n: 22, correta: "A", resumo: "Nem toda consulta precisa do pipeline completo: selecionar só os agentes necessários e usá-los apenas quando agregam valor evita custo desnecessário sem sacrificar qualidade nas consultas que realmente precisam de mais agentes.", bloom: "Avaliar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "seleção dinâmica de agentes (só os necessários) em vez de rodar o pipeline completo sempre", topicos: ["Coordenador e Subagentes"], arquetipos: { B: "extremo-vs-meio", C: "sinal-nao-confiavel", D: "camada-alvo-errado" } },
  { n: 23, correta: "C", resumo: "O campo `description` de um `AgentDefinition` é o que o coordenador lê para decidir se invoca aquele agente — é uma descrição de ferramenta disfarçada, e por isso segue as mesmas regras: propósito claro, formato de entrada esperado e limites de uso.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "`description` de um subagente é lida pelo coordenador para decidir invocação — mesmas regras de uma tool description", topicos: ["Descrições de Tools", "Spawn de Subagentes"], arquetipos: { A: "camada-alvo-errado", B: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 24, correta: "A", resumo: "Fork de sessão cria um novo identificador de sessão preservando o histórico da conversa até aquele ponto, sem afetar a sessão original — diferente de `/clear` (zera), `--continue`/`--resume` (retoma a mesma sessão) ou `/compact` (resume para economizar tokens).", bloom: "Aplicar", dificuldade: "Difícil", cenario: "S4 — Developer Productivity", principio: "fork cria uma nova sessão a partir do histórico atual, preservando a original intacta", topicos: ["Resume e Fork de Sessão"], arquetipos: { B: "camada-alvo-errado", C: "feature-inexistente-verossimil", D: "camada-alvo-errado" } },
  { n: 25, correta: "D", resumo: "Fluxo sequencial deve ser usado quando cada etapa consome a saída da etapa anterior — paralelizar etapas dependentes produz entrada vazia para quem viria depois, e comunicação direta entre subagentes não existe em hub-and-spoke.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "usar fluxo sequencial quando uma etapa depende da saída da etapa anterior", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "camada-alvo-errado", B: "feature-inexistente-verossimil", C: "vazio-ausente" } },
  { n: 26, correta: "A", resumo: "É o coordenador atuando como ponto único de passagem que torna o fluxo e as falhas de cada subagente inspecionáveis — subagentes têm contexto isolado entre si, não compartilhado, e comunicação direta destruiria essa observabilidade.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S3 — Multi-Agent Research System", principio: "coordenador como ponto único de passagem é o que viabiliza observabilidade de falhas", topicos: ["Coordenador e Subagentes"], arquetipos: { B: "feature-inexistente-verossimil", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 27, correta: "C", resumo: "Depois de uma chamada de ferramenta, o resultado deve ser anexado como um bloco `tool_result` tipado, casado ao `tool_use_id` correspondente, e a API é chamada de novo com a conversa atualizada — o loop continua até `stop_reason` virar `end_turn`.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "resultado de tool call é anexado como bloco `tool_result` tipado, casado ao `tool_use_id`, não texto livre", topicos: ["Loop Agêntico"], arquetipos: { A: "montante-jusante", B: "probabilistico-vs-garantia", D: "camada-alvo-errado" } },
  { n: 28, correta: "A", resumo: "Definir o objetivo e o critério do que conta como resposta completa (quais caminhos, cobertura de testes) deixa a estratégia de busca livre para o subagente decidir, sem perder controle sobre o que precisa ser entregue — diferente de fixar a sequência exata de tools.", bloom: "Avaliar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "definir objetivo + critério de completude adapta sem perder controle, melhor que fixar a sequência de tools", topicos: ["Enforcement de Workflow"], arquetipos: { B: "extremo-vs-meio", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 29, correta: "C", resumo: "Para detectar decomposição fraca antes que o trabalho comece, implementa-se uma tool que revisa a lista de subtarefas antes de prosseguir para gerá-las de fato — verificar só na agregação final é tarde demais, os subagentes já rodaram e gastaram.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "revisar a decomposição antes de delegar, não só na agregação final do resultado", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "montante-jusante", B: "extremo-vs-meio", D: "sinal-nao-confiavel" } },
  { n: 30, correta: "A", resumo: "Ao encerrar uma sessão, o ambiente devolve um identificador de sessão que permite retomá-la depois (`/resume` ou `claude --resume`), restaurando o histórico da conversa — não há replay automático de tool calls nem gravação como markdown no repositório.", bloom: "Lembrar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "sessão encerrada é retomável pelo `session_id`, restaurando o histórico da conversa", topicos: ["Resume e Fork de Sessão"], arquetipos: { B: "feature-inexistente-verossimil", C: "feature-inexistente-verossimil" } },
  { n: 31, correta: "C", resumo: "Ao agregar resultados de múltiplos agentes que discordam entre si, a regra de conflito precisa ser explícita e verificável — por exemplo, preferir o dado mais específico — em vez de descartar tudo que diverge ou empurrar o conflito bruto para o leitor.", bloom: "Avaliar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "agregação de resultados conflitantes precisa de regra de resolução explícita (ex.: preferir o dado mais específico)", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "vazio-ausente", B: "camada-alvo-errado", D: "sinal-nao-confiavel" } },
  { n: 32, correta: "A", resumo: "De todos os campos de um `AgentDefinition`, só `allowedTools`/`disallowedTools` são de fato aplicados na plataforma — os demais (nome, descrição, system prompt) orientam a seleção e o comportamento, mas não impedem nada estruturalmente.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "`allowedTools`/`disallowedTools` é o único campo de `AgentDefinition` com enforcement de plataforma", topicos: ["Spawn de Subagentes", "Tool Choice"], arquetipos: { B: "camada-alvo-errado", C: "camada-alvo-errado", D: "probabilistico-vs-garantia" } },
  { n: 33, correta: "B", resumo: "`stop_reason: \"end_turn\"` indica que o agente decidiu devolver um resultado final ao usuário, encerrando o loop — diferente de ficar sem tokens (outro motivo de parada) ou de querer chamar uma tool (`tool_use`).", bloom: "Lembrar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "`end_turn` sinaliza resposta final do agente, encerrando o loop", topicos: ["Loop Agêntico"], arquetipos: { A: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 34, correta: "D", resumo: "Passar achados brutos entre agentes como um único bloco de texto perde a atribuição de origem — quando o texto final é escrito, já não dá mais para saber qual agente disse o quê. A correção é usar objetos estruturados em que conteúdo e metadado de origem viajam juntos.", bloom: "Analisar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "objetos estruturados (conteúdo + metadado de origem) preservam atribuição entre agentes; texto solto não", topicos: ["Descrições de Tools"], arquetipos: { A: "camada-alvo-errado", B: "camada-alvo-errado", C: "camada-alvo-errado" } },
  { n: 35, correta: "C", resumo: "Módulos de trabalho independentes, sem dependência compartilhada entre si, devem rodar como subagentes em paralelo — fundir tudo num agente único ou rodar terminais manuais descarta o paralelismo sem necessidade.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "tarefas independentes sem dependência compartilhada rodam em paralelo, reduzindo tempo de relógio", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "over-engineering", B: "feature-inexistente-verossimil", D: "extremo-vs-meio" } },
  { n: 36, correta: "C", resumo: "Como cada subagente roda seu próprio loop interno de forma opaca para o coordenador, qualquer coisa que precise ser visível — passos intermediários, decisões — precisa ser incluída explicitamente na saída final que o subagente devolve.", bloom: "Analisar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "o loop interno de um subagente é opaco ao coordenador — o que precisa ser visível tem que estar na saída estruturada", topicos: ["Spawn de Subagentes"], arquetipos: { A: "feature-inexistente-verossimil", B: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 37, correta: "D", resumo: "Um gate programático (hook `PreToolUse` casado com a condição de pré-requisito) torna estruturalmente impossível pular uma etapa obrigatória — checar depois, reordenar no prompt ou reescrever a descrição da tool não bloqueiam a chamada de fato.", bloom: "Aplicar", dificuldade: "Difícil", cenario: "S4 — Developer Productivity", principio: "gate programático via hook `PreToolUse` torna impossível pular um pré-requisito, não apenas desencorajado", topicos: ["Hooks", "Enforcement de Workflow"], arquetipos: { A: "montante-jusante", B: "probabilistico-vs-garantia", C: "probabilistico-vs-garantia" } },
  { n: 38, correta: "D", resumo: "Um plano de investigação adaptativo trata cada achado como entrada para a próxima decisão, não apenas como dado coletado — é um sinal que redesenha o que precisa ser feito a seguir, ao contrário de um plano com etapas fixas de antemão.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "cada achado intermediário é um sinal que redefine o próximo passo, não só dado a acumular", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "camada-alvo-errado", B: "extremo-vs-meio", C: "camada-alvo-errado" } },
  { n: 39, correta: "A", resumo: "Um prompt de coordenador bem desenhado cobre decomposição (quebrar em subtarefas), delegação (mandar cada uma para um subagente) e proíbe explicitamente o coordenador de executar o trabalho ele mesmo — agregação é responsabilidade separada.", bloom: "Aplicar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "prompt de coordenador define decomposição e delegação, e proíbe o coordenador de executar diretamente", topicos: ["Coordenador e Subagentes"], arquetipos: { B: "camada-alvo-errado", C: "camada-alvo-errado", D: "vazio-ausente" } },
  { n: 40, correta: "C", resumo: "O atributo `context: fork` no frontmatter de uma skill ou slash command faz com que ela execute em contexto de subagente isolado, evitando que o processamento intermediário polua o estado da sessão principal.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "`context: fork` isola a execução de uma skill/command em contexto de subagente, sem poluir a sessão principal", topicos: ["Hierarquia CLAUDE.md", "Spawn de Subagentes"], arquetipos: { A: "camada-alvo-errado", B: "camada-alvo-errado", D: "extremo-vs-meio" } },
  { n: 41, correta: "C", resumo: "Depois de uma pausa longa, o mais eficiente é injetar no contexto exatamente a lista de arquivos que mudaram e pedir uma releitura dirigida a eles — reler tudo funciona mas desperdiça contexto, e confiar num resumo antigo arrisca trabalhar com informação desatualizada.", bloom: "Avaliar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "re-análise dirigida (injetar só os arquivos que mudaram) é mais eficiente que reler tudo ou confiar em resumo antigo", topicos: ["Resume e Fork de Sessão", "Contexto de Codebase"], arquetipos: { A: "camada-alvo-errado", B: "over-engineering", D: "sinal-nao-confiavel" } },
  { n: 42, correta: "B", resumo: "Quatro políticas independentes devem ser lidas em paralelo, uma por agente, e só a comparação final com as regras de retenção — que depende das quatro saídas — é o passo de síntese sequencial.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S6 — Structured Data Extraction", principio: "leituras independentes em paralelo, síntese sequencial só na etapa que de fato depende de todas as saídas", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "camada-alvo-errado", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 43, correta: "B", resumo: "Rodar testes exige executar comandos (Bash); se o `allowedTools` do subagente só permite leitura e busca, existe um descasamento estrutural entre o que o prompt pede e o que a plataforma de fato permite a ele fazer.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "descasamento entre o que o prompt pede e o `allowedTools` configurado impede a tarefa, independente da redação do prompt", topicos: ["Spawn de Subagentes", "Tool Choice"], arquetipos: { A: "probabilistico-vs-garantia", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 44, correta: "C", resumo: "Um objeto de estado estruturado, mantido fora do histórico da conversa, permanece autoritativo mesmo quando a conversa é compactada — a compactação resume o histórico, mas não deveria tocar o estado que vive fora dele.", bloom: "Aplicar", dificuldade: "Difícil", cenario: "S4 — Developer Productivity", principio: "estado estruturado fora do histórico da conversa sobrevive à compactação, ao contrário do histórico em si", topicos: ["Resume e Fork de Sessão", "Contexto Longo"], arquetipos: { A: "camada-alvo-errado", B: "montante-jusante", D: "extremo-vs-meio" } },
  { n: 45, correta: "A", resumo: "\"Task\" é o nome legado da mesma ferramenta hoje chamada \"Agent\": ela spawna um subagente com contexto isolado, system prompt e conjunto de tools próprios — os dois nomes se referem ao mesmo mecanismo, não a funcionalidades diferentes.", bloom: "Lembrar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "\"Task\" é o nome legado de \"Agent\" — mesma ferramenta de spawn de subagente", topicos: ["Spawn de Subagentes"], arquetipos: { B: "camada-alvo-errado", D: "feature-inexistente-verossimil" } },
  { n: 46, correta: "A", resumo: "Um limite de valor que nunca pode ser ultrapassado é regra de negócio e deve ser aplicada em código, antes da tool ser chamada — independe de quão insistente for o pedido do usuário, já que few-shot, negrito e temperatura só influenciam tendência, não garantem nada.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S1 — Customer Support Resolution Agent", principio: "limite absoluto de negócio (\"nunca\") precisa ser gate em código, não instrução por prompt", topicos: ["Enforcement de Workflow"], arquetipos: { B: "probabilistico-vs-garantia", C: "probabilistico-vs-garantia", D: "probabilistico-vs-garantia" } },
  { n: 47, correta: "B", resumo: "A saída de um subagente deve ser um objeto estruturado que mantém conteúdo e metadado juntos — campos como id, tipo, confiança e detalhes de origem — o que viabiliza rastreabilidade; prosa ou saída crua de tool perdem essa ligação.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "objetos estruturados com metadado de origem (id, tipo, confiança, fonte) viabilizam rastreabilidade", topicos: ["Descrições de Tools"], arquetipos: { A: "camada-alvo-errado", C: "camada-alvo-errado", D: "vazio-ausente" } },
  { n: 48, correta: "B", resumo: "Quando o escopo não é conhecido de antemão, subtarefas precisam ser geradas dinamicamente à medida que a investigação avança, parando quando nenhum sinal novo aparece — uma lista fixa decidida cedo demais é o mesmo erro de decomposição estreita com outro nome.", bloom: "Avaliar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "escopo desconhecido de antemão exige geração dinâmica de subtarefas, com critério de parada por ausência de sinal novo", topicos: ["Decomposição de Tarefas"], arquetipos: { A: "extremo-vs-meio", C: "enumerar-vs-generalizar", D: "over-engineering" } },
  { n: 49, correta: "A", resumo: "O Plan Mode do Claude Code permite que o agente analise e proponha mudanças sem modificar arquivos nem executar comandos — é literalmente o modo desenhado para analisar antes de tocar em qualquer coisa.", bloom: "Lembrar", dificuldade: "Fácil", cenario: "S4 — Developer Productivity", principio: "Plan Mode analisa sem modificar arquivos nem executar comandos", topicos: ["Plan Mode"], arquetipos: { B: "camada-alvo-errado", C: "extremo-vs-meio", D: "camada-alvo-errado" } },
  { n: 50, correta: "D", resumo: "O histórico de conversa pode ser compactado ou truncado a qualquer momento, então não é um registro confiável de quais etapas já foram concluídas — o requisito de nunca refazer trabalho pede um estado externo durável, não uma leitura do histórico.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "histórico de conversa não é registro confiável de progresso — pode ser compactado ou truncado", topicos: ["Resume e Fork de Sessão", "Contexto Longo"], arquetipos: { A: "camada-alvo-errado", B: "sinal-nao-confiavel", C: "vazio-ausente" } },
  { n: 51, correta: "B", resumo: "Combinar as saídas de múltiplos agentes numa resposta única e coerente é a etapa de agregação de resultados do ciclo de vida da tarefa — distinta da seleção de agentes, da configuração de escopo de permissão e da decomposição inicial.", bloom: "Lembrar", dificuldade: "Fácil", cenario: "S3 — Multi-Agent Research System", principio: "agregação de resultados é a etapa que combina saídas de múltiplos agentes numa resposta coerente", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "camada-alvo-errado", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
  { n: 52, correta: "C", resumo: "Como o loop interno de um subagente paralelo não é observável ao vivo, o rastro do que ele fez precisa vir na própria saída estruturada, para o coordenador inspecionar depois — abandonar o paralelismo não resolve, só troca latência por uma visibilidade que ainda não existiria.", bloom: "Analisar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "rastro de execução de subagente paralelo precisa estar na saída estruturada, já que o loop interno não é observável ao vivo", topicos: ["Spawn de Subagentes"], arquetipos: { A: "camada-alvo-errado", B: "extremo-vs-meio", D: "camada-alvo-errado" } },
  { n: 53, correta: "C", resumo: "Um `AgentDefinition` existe justamente para delimitar o papel do subagente antes da primeira mensagem — identidade, regras de operação e fronteiras — sem isso nem a seleção pelo coordenador nem o comportamento do agente ficam limitados.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "`AgentDefinition` delimita papel, regras e fronteiras do subagente antes de qualquer invocação", topicos: ["Spawn de Subagentes"], arquetipos: { A: "camada-alvo-errado", B: "feature-inexistente-verossimil", D: "extremo-vs-meio" } },
  { n: 54, correta: "A", resumo: "Cobertura completa é validada em dois pontos: uma checagem da lista de subtarefas antes de delegar e uma checagem de lacunas na agregação, antes de o relatório final sair — subagentes isolados não conseguem ver o que falta, e depender do usuário perceber transfere o defeito para fora do sistema.", bloom: "Avaliar", dificuldade: "Difícil", cenario: "S3 — Multi-Agent Research System", principio: "cobertura é validada tanto antes de delegar quanto na agregação final, nunca só delegada a subagentes isolados ou ao usuário", topicos: ["Decomposição de Tarefas"], arquetipos: { B: "camada-alvo-errado", C: "montante-jusante", D: "camada-alvo-errado" } },
  { n: 55, correta: "C", resumo: "Ao retomar uma sessão, o modelo não sabe quanto tempo passou nem o que pode ter mudado desde então — o contexto retomado pode estar silenciosamente desatualizado, e nenhuma configuração de expiração ou releitura automática resolve isso sozinha.", bloom: "Analisar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "sessão retomada pode estar silenciosamente desatualizada — o modelo desconhece o tempo decorrido", topicos: ["Resume e Fork de Sessão"], arquetipos: { A: "camada-alvo-errado", B: "feature-inexistente-verossimil", D: "sinal-nao-confiavel" } },
  { n: 56, correta: "C", resumo: "A escolha entre o agente principal bloquear esperando um subagente ou paralelizar depende de existir ou não dependência entre eles — não é sempre uma coisa nem sempre outra, e subagentes paralelos continuam isolados entre si.", bloom: "Aplicar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "bloquear vs. paralelizar a espera por um subagente depende da dependência entre as tarefas, não é fixo", topicos: ["Spawn de Subagentes"], arquetipos: { A: "extremo-vs-meio", B: "extremo-vs-meio", D: "feature-inexistente-verossimil" } },
  { n: 57, correta: "D", resumo: "O hook `PostToolUse` roda depois que a ferramenta já executou, sendo o lugar certo para registrar o resultado e atualizar estado que gates posteriores vão consultar — bloquear ou reescrever parâmetros antes da execução é papel do `PreToolUse`.", bloom: "Aplicar", dificuldade: "Difícil", cenario: "S4 — Developer Productivity", principio: "`PostToolUse` registra resultado/estado depois da execução, para gates posteriores consultarem", topicos: ["Hooks"], arquetipos: { A: "camada-alvo-errado", B: "camada-alvo-errado", C: "feature-inexistente-verossimil" } },
  { n: 58, correta: "B", resumo: "É o coordenador como ponto único de passagem que permite aplicar e auditar uma política de fluxo de informação num só lugar — sem ele, cada subagente aplicaria sua própria regra de forma inconsistente e não auditável centralmente.", bloom: "Analisar", dificuldade: "Médio", cenario: "S3 — Multi-Agent Research System", principio: "política de fluxo de informação sensível é aplicável e auditável só quando centralizada no coordenador", topicos: ["Coordenador e Subagentes"], arquetipos: { A: "camada-alvo-errado", C: "extremo-vs-meio", D: "camada-alvo-errado" } },
  { n: 59, correta: "D", resumo: "A escolha de arquitetura precisa ser proporcional a escopo, risco e necessidade de aprovação humana — para uma mudança pequena, de risco baixo e com verificação automática já existente, execução direta basta; plan mode ou fluxo multi-fase seriam cerimônia sem retorno.", bloom: "Avaliar", dificuldade: "Médio", cenario: "S4 — Developer Productivity", principio: "arquitetura de revisão deve ser proporcional a escopo, risco e necessidade de aprovação humana — nem tudo pede o mecanismo mais pesado", topicos: ["Plan Mode", "Enforcement de Workflow"], arquetipos: { A: "extremo-vs-meio", B: "over-engineering", C: "over-engineering" } },
  { n: 60, correta: "A", resumo: "O modelo frequentemente devolve texto junto com um bloco `tool_use` no mesmo turno; parar o loop assim que aparece qualquer texto faria o programa desistir antes mesmo de a ferramenta ser executada.", bloom: "Analisar", dificuldade: "Médio", cenario: "S1 — Customer Support Resolution Agent", principio: "texto e `tool_use` podem coexistir no mesmo turno — parar no primeiro texto aborta antes da execução real", topicos: ["Loop Agêntico"], arquetipos: { B: "camada-alvo-errado", C: "camada-alvo-errado", D: "camada-alvo-errado" } },
];

export default D1;
